version: 2

build:
  os: ubuntu-22.04
  tools:
    python: 3.10

submodules:
  include: all

python:
  install:
    - requirements: requirements.yml

sphinx:
  configuration: source/conf.py
  builder: html

formats:
  - htmlzip

