name: 'mirror'
on:
  push:
    branches:
        - __mirror
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror-to-github
        id: mirror-to-github
        uses: bridgelightcloud/github-mirror-action@v2
        with:
          origin: https://gitee.com/ajz34/ajz34.readthedocs.io.git
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
